services:
  - type: web
    name: plataforma-monitoreo
    env: python
    region: ohio
    plan: free
    buildCommand: "pip install -r requirements.txt && python init_db.py"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
